# Generated by Django 4.0.4 on 2022-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(default=0, max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('class_name', models.CharField(default='', max_length=10)),
                ('mark', models.IntegerField(default=0, max_length=3)),
                ('gender', models.CharField(default='male', max_length=6)),
            ],
        ),
    ]
